# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\alego\projects\Axiom-T

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\alego\projects\Axiom-T\build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\alego\projects\Axiom-T\build\CMakeFiles C:\Users\alego\projects\Axiom-T\build\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\alego\projects\Axiom-T\build\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ThermoMath

# Build rule for target.
ThermoMath: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 ThermoMath
.PHONY : ThermoMath

# fast build rule for target.
ThermoMath/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ThermoMath.dir\build.make CMakeFiles/ThermoMath.dir/build
.PHONY : ThermoMath/fast

#=============================================================================
# Target rules for targets named AxiomT

# Build rule for target.
AxiomT: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 AxiomT
.PHONY : AxiomT

# fast build rule for target.
AxiomT/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AxiomT.dir\build.make CMakeFiles/AxiomT.dir/build
.PHONY : AxiomT/fast

#=============================================================================
# Target rules for targets named ThermoTests

# Build rule for target.
ThermoTests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 ThermoTests
.PHONY : ThermoTests

# fast build rule for target.
ThermoTests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ThermoTests.dir\build.make CMakeFiles/ThermoTests.dir/build
.PHONY : ThermoTests/fast

main.obj: main.cpp.obj
.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AxiomT.dir\build.make CMakeFiles/AxiomT.dir/main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AxiomT.dir\build.make CMakeFiles/AxiomT.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AxiomT.dir\build.make CMakeFiles/AxiomT.dir/main.cpp.s
.PHONY : main.cpp.s

src/Energy.obj: src/Energy.cpp.obj
.PHONY : src/Energy.obj

# target to build an object file
src/Energy.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ThermoMath.dir\build.make CMakeFiles/ThermoMath.dir/src/Energy.cpp.obj
.PHONY : src/Energy.cpp.obj

src/Energy.i: src/Energy.cpp.i
.PHONY : src/Energy.i

# target to preprocess a source file
src/Energy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ThermoMath.dir\build.make CMakeFiles/ThermoMath.dir/src/Energy.cpp.i
.PHONY : src/Energy.cpp.i

src/Energy.s: src/Energy.cpp.s
.PHONY : src/Energy.s

# target to generate assembly for a file
src/Energy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ThermoMath.dir\build.make CMakeFiles/ThermoMath.dir/src/Energy.cpp.s
.PHONY : src/Energy.cpp.s

src/IdealGas.obj: src/IdealGas.cpp.obj
.PHONY : src/IdealGas.obj

# target to build an object file
src/IdealGas.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ThermoMath.dir\build.make CMakeFiles/ThermoMath.dir/src/IdealGas.cpp.obj
.PHONY : src/IdealGas.cpp.obj

src/IdealGas.i: src/IdealGas.cpp.i
.PHONY : src/IdealGas.i

# target to preprocess a source file
src/IdealGas.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ThermoMath.dir\build.make CMakeFiles/ThermoMath.dir/src/IdealGas.cpp.i
.PHONY : src/IdealGas.cpp.i

src/IdealGas.s: src/IdealGas.cpp.s
.PHONY : src/IdealGas.s

# target to generate assembly for a file
src/IdealGas.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ThermoMath.dir\build.make CMakeFiles/ThermoMath.dir/src/IdealGas.cpp.s
.PHONY : src/IdealGas.cpp.s

src/Mass.obj: src/Mass.cpp.obj
.PHONY : src/Mass.obj

# target to build an object file
src/Mass.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ThermoMath.dir\build.make CMakeFiles/ThermoMath.dir/src/Mass.cpp.obj
.PHONY : src/Mass.cpp.obj

src/Mass.i: src/Mass.cpp.i
.PHONY : src/Mass.i

# target to preprocess a source file
src/Mass.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ThermoMath.dir\build.make CMakeFiles/ThermoMath.dir/src/Mass.cpp.i
.PHONY : src/Mass.cpp.i

src/Mass.s: src/Mass.cpp.s
.PHONY : src/Mass.s

# target to generate assembly for a file
src/Mass.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ThermoMath.dir\build.make CMakeFiles/ThermoMath.dir/src/Mass.cpp.s
.PHONY : src/Mass.cpp.s

src/NumericalSolver.obj: src/NumericalSolver.cpp.obj
.PHONY : src/NumericalSolver.obj

# target to build an object file
src/NumericalSolver.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ThermoMath.dir\build.make CMakeFiles/ThermoMath.dir/src/NumericalSolver.cpp.obj
.PHONY : src/NumericalSolver.cpp.obj

src/NumericalSolver.i: src/NumericalSolver.cpp.i
.PHONY : src/NumericalSolver.i

# target to preprocess a source file
src/NumericalSolver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ThermoMath.dir\build.make CMakeFiles/ThermoMath.dir/src/NumericalSolver.cpp.i
.PHONY : src/NumericalSolver.cpp.i

src/NumericalSolver.s: src/NumericalSolver.cpp.s
.PHONY : src/NumericalSolver.s

# target to generate assembly for a file
src/NumericalSolver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ThermoMath.dir\build.make CMakeFiles/ThermoMath.dir/src/NumericalSolver.cpp.s
.PHONY : src/NumericalSolver.cpp.s

src/Power.obj: src/Power.cpp.obj
.PHONY : src/Power.obj

# target to build an object file
src/Power.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ThermoMath.dir\build.make CMakeFiles/ThermoMath.dir/src/Power.cpp.obj
.PHONY : src/Power.cpp.obj

src/Power.i: src/Power.cpp.i
.PHONY : src/Power.i

# target to preprocess a source file
src/Power.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ThermoMath.dir\build.make CMakeFiles/ThermoMath.dir/src/Power.cpp.i
.PHONY : src/Power.cpp.i

src/Power.s: src/Power.cpp.s
.PHONY : src/Power.s

# target to generate assembly for a file
src/Power.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ThermoMath.dir\build.make CMakeFiles/ThermoMath.dir/src/Power.cpp.s
.PHONY : src/Power.cpp.s

src/Pressure.obj: src/Pressure.cpp.obj
.PHONY : src/Pressure.obj

# target to build an object file
src/Pressure.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ThermoMath.dir\build.make CMakeFiles/ThermoMath.dir/src/Pressure.cpp.obj
.PHONY : src/Pressure.cpp.obj

src/Pressure.i: src/Pressure.cpp.i
.PHONY : src/Pressure.i

# target to preprocess a source file
src/Pressure.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ThermoMath.dir\build.make CMakeFiles/ThermoMath.dir/src/Pressure.cpp.i
.PHONY : src/Pressure.cpp.i

src/Pressure.s: src/Pressure.cpp.s
.PHONY : src/Pressure.s

# target to generate assembly for a file
src/Pressure.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ThermoMath.dir\build.make CMakeFiles/ThermoMath.dir/src/Pressure.cpp.s
.PHONY : src/Pressure.cpp.s

src/Temperature.obj: src/Temperature.cpp.obj
.PHONY : src/Temperature.obj

# target to build an object file
src/Temperature.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ThermoMath.dir\build.make CMakeFiles/ThermoMath.dir/src/Temperature.cpp.obj
.PHONY : src/Temperature.cpp.obj

src/Temperature.i: src/Temperature.cpp.i
.PHONY : src/Temperature.i

# target to preprocess a source file
src/Temperature.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ThermoMath.dir\build.make CMakeFiles/ThermoMath.dir/src/Temperature.cpp.i
.PHONY : src/Temperature.cpp.i

src/Temperature.s: src/Temperature.cpp.s
.PHONY : src/Temperature.s

# target to generate assembly for a file
src/Temperature.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ThermoMath.dir\build.make CMakeFiles/ThermoMath.dir/src/Temperature.cpp.s
.PHONY : src/Temperature.cpp.s

src/Volume.obj: src/Volume.cpp.obj
.PHONY : src/Volume.obj

# target to build an object file
src/Volume.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ThermoMath.dir\build.make CMakeFiles/ThermoMath.dir/src/Volume.cpp.obj
.PHONY : src/Volume.cpp.obj

src/Volume.i: src/Volume.cpp.i
.PHONY : src/Volume.i

# target to preprocess a source file
src/Volume.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ThermoMath.dir\build.make CMakeFiles/ThermoMath.dir/src/Volume.cpp.i
.PHONY : src/Volume.cpp.i

src/Volume.s: src/Volume.cpp.s
.PHONY : src/Volume.s

# target to generate assembly for a file
src/Volume.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ThermoMath.dir\build.make CMakeFiles/ThermoMath.dir/src/Volume.cpp.s
.PHONY : src/Volume.cpp.s

tests/catch2/catch_amalgamated.obj: tests/catch2/catch_amalgamated.cpp.obj
.PHONY : tests/catch2/catch_amalgamated.obj

# target to build an object file
tests/catch2/catch_amalgamated.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ThermoTests.dir\build.make CMakeFiles/ThermoTests.dir/tests/catch2/catch_amalgamated.cpp.obj
.PHONY : tests/catch2/catch_amalgamated.cpp.obj

tests/catch2/catch_amalgamated.i: tests/catch2/catch_amalgamated.cpp.i
.PHONY : tests/catch2/catch_amalgamated.i

# target to preprocess a source file
tests/catch2/catch_amalgamated.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ThermoTests.dir\build.make CMakeFiles/ThermoTests.dir/tests/catch2/catch_amalgamated.cpp.i
.PHONY : tests/catch2/catch_amalgamated.cpp.i

tests/catch2/catch_amalgamated.s: tests/catch2/catch_amalgamated.cpp.s
.PHONY : tests/catch2/catch_amalgamated.s

# target to generate assembly for a file
tests/catch2/catch_amalgamated.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ThermoTests.dir\build.make CMakeFiles/ThermoTests.dir/tests/catch2/catch_amalgamated.cpp.s
.PHONY : tests/catch2/catch_amalgamated.cpp.s

tests/test_ideal_gas.obj: tests/test_ideal_gas.cpp.obj
.PHONY : tests/test_ideal_gas.obj

# target to build an object file
tests/test_ideal_gas.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ThermoTests.dir\build.make CMakeFiles/ThermoTests.dir/tests/test_ideal_gas.cpp.obj
.PHONY : tests/test_ideal_gas.cpp.obj

tests/test_ideal_gas.i: tests/test_ideal_gas.cpp.i
.PHONY : tests/test_ideal_gas.i

# target to preprocess a source file
tests/test_ideal_gas.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ThermoTests.dir\build.make CMakeFiles/ThermoTests.dir/tests/test_ideal_gas.cpp.i
.PHONY : tests/test_ideal_gas.cpp.i

tests/test_ideal_gas.s: tests/test_ideal_gas.cpp.s
.PHONY : tests/test_ideal_gas.s

# target to generate assembly for a file
tests/test_ideal_gas.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ThermoTests.dir\build.make CMakeFiles/ThermoTests.dir/tests/test_ideal_gas.cpp.s
.PHONY : tests/test_ideal_gas.cpp.s

tests/test_numerical_solver.obj: tests/test_numerical_solver.cpp.obj
.PHONY : tests/test_numerical_solver.obj

# target to build an object file
tests/test_numerical_solver.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ThermoTests.dir\build.make CMakeFiles/ThermoTests.dir/tests/test_numerical_solver.cpp.obj
.PHONY : tests/test_numerical_solver.cpp.obj

tests/test_numerical_solver.i: tests/test_numerical_solver.cpp.i
.PHONY : tests/test_numerical_solver.i

# target to preprocess a source file
tests/test_numerical_solver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ThermoTests.dir\build.make CMakeFiles/ThermoTests.dir/tests/test_numerical_solver.cpp.i
.PHONY : tests/test_numerical_solver.cpp.i

tests/test_numerical_solver.s: tests/test_numerical_solver.cpp.s
.PHONY : tests/test_numerical_solver.s

# target to generate assembly for a file
tests/test_numerical_solver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ThermoTests.dir\build.make CMakeFiles/ThermoTests.dir/tests/test_numerical_solver.cpp.s
.PHONY : tests/test_numerical_solver.cpp.s

tests/test_pressure.obj: tests/test_pressure.cpp.obj
.PHONY : tests/test_pressure.obj

# target to build an object file
tests/test_pressure.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ThermoTests.dir\build.make CMakeFiles/ThermoTests.dir/tests/test_pressure.cpp.obj
.PHONY : tests/test_pressure.cpp.obj

tests/test_pressure.i: tests/test_pressure.cpp.i
.PHONY : tests/test_pressure.i

# target to preprocess a source file
tests/test_pressure.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ThermoTests.dir\build.make CMakeFiles/ThermoTests.dir/tests/test_pressure.cpp.i
.PHONY : tests/test_pressure.cpp.i

tests/test_pressure.s: tests/test_pressure.cpp.s
.PHONY : tests/test_pressure.s

# target to generate assembly for a file
tests/test_pressure.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ThermoTests.dir\build.make CMakeFiles/ThermoTests.dir/tests/test_pressure.cpp.s
.PHONY : tests/test_pressure.cpp.s

tests/test_temperature.obj: tests/test_temperature.cpp.obj
.PHONY : tests/test_temperature.obj

# target to build an object file
tests/test_temperature.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ThermoTests.dir\build.make CMakeFiles/ThermoTests.dir/tests/test_temperature.cpp.obj
.PHONY : tests/test_temperature.cpp.obj

tests/test_temperature.i: tests/test_temperature.cpp.i
.PHONY : tests/test_temperature.i

# target to preprocess a source file
tests/test_temperature.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ThermoTests.dir\build.make CMakeFiles/ThermoTests.dir/tests/test_temperature.cpp.i
.PHONY : tests/test_temperature.cpp.i

tests/test_temperature.s: tests/test_temperature.cpp.s
.PHONY : tests/test_temperature.s

# target to generate assembly for a file
tests/test_temperature.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ThermoTests.dir\build.make CMakeFiles/ThermoTests.dir/tests/test_temperature.cpp.s
.PHONY : tests/test_temperature.cpp.s

tests/test_units.obj: tests/test_units.cpp.obj
.PHONY : tests/test_units.obj

# target to build an object file
tests/test_units.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ThermoTests.dir\build.make CMakeFiles/ThermoTests.dir/tests/test_units.cpp.obj
.PHONY : tests/test_units.cpp.obj

tests/test_units.i: tests/test_units.cpp.i
.PHONY : tests/test_units.i

# target to preprocess a source file
tests/test_units.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ThermoTests.dir\build.make CMakeFiles/ThermoTests.dir/tests/test_units.cpp.i
.PHONY : tests/test_units.cpp.i

tests/test_units.s: tests/test_units.cpp.s
.PHONY : tests/test_units.s

# target to generate assembly for a file
tests/test_units.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ThermoTests.dir\build.make CMakeFiles/ThermoTests.dir/tests/test_units.cpp.s
.PHONY : tests/test_units.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... AxiomT
	@echo ... ThermoMath
	@echo ... ThermoTests
	@echo ... main.obj
	@echo ... main.i
	@echo ... main.s
	@echo ... src/Energy.obj
	@echo ... src/Energy.i
	@echo ... src/Energy.s
	@echo ... src/IdealGas.obj
	@echo ... src/IdealGas.i
	@echo ... src/IdealGas.s
	@echo ... src/Mass.obj
	@echo ... src/Mass.i
	@echo ... src/Mass.s
	@echo ... src/NumericalSolver.obj
	@echo ... src/NumericalSolver.i
	@echo ... src/NumericalSolver.s
	@echo ... src/Power.obj
	@echo ... src/Power.i
	@echo ... src/Power.s
	@echo ... src/Pressure.obj
	@echo ... src/Pressure.i
	@echo ... src/Pressure.s
	@echo ... src/Temperature.obj
	@echo ... src/Temperature.i
	@echo ... src/Temperature.s
	@echo ... src/Volume.obj
	@echo ... src/Volume.i
	@echo ... src/Volume.s
	@echo ... tests/catch2/catch_amalgamated.obj
	@echo ... tests/catch2/catch_amalgamated.i
	@echo ... tests/catch2/catch_amalgamated.s
	@echo ... tests/test_ideal_gas.obj
	@echo ... tests/test_ideal_gas.i
	@echo ... tests/test_ideal_gas.s
	@echo ... tests/test_numerical_solver.obj
	@echo ... tests/test_numerical_solver.i
	@echo ... tests/test_numerical_solver.s
	@echo ... tests/test_pressure.obj
	@echo ... tests/test_pressure.i
	@echo ... tests/test_pressure.s
	@echo ... tests/test_temperature.obj
	@echo ... tests/test_temperature.i
	@echo ... tests/test_temperature.s
	@echo ... tests/test_units.obj
	@echo ... tests/test_units.i
	@echo ... tests/test_units.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

